# Generated by Django 5.1 on 2024-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=20)),
                ("income", models.PositiveIntegerField()),
                ("expenses", models.PositiveIntegerField()),
                ("profit", models.PositiveIntegerField()),
                ("tax", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Финансовые данные",
                "verbose_name_plural": "Финансовые данные",
                "ordering": ["month"],
            },
        ),
    ]
